### ISSUE TITLE
爱奇艺的视频貌似解析不了了

### ISSUE THREAD

**Issue by RockWithBoA** [keygle/parseVideo#7]
页面输出结果类似：
Notice: Undefined index: data in ...\parseVideo\core\iqiyi.class.php on line 103
Array
(
    [title] => 晓松奇谈之胜利下的阴影（3）失贞与叛国
)

**Comment by ysmoe** [comment]
同样，我这边的配置也是只能返回视频名称了~

**Comment by fr0zenrain** [comment]
爱奇艺最近老换算法，you-get那边更新例如。

**Comment by xyuanmu** [comment]
很简单，打开 core -> iqiyi.class.php 修改6、7行内容即可：
```php
OLD:
	static public $deadpara = 1000;
	static public $enc_key =  "ts56gh";

NEW:
	static public $deadpara = 832;
	static public $enc_key =  "a6f2a01ab9ad4510be0449fab528b82c";
```

**Comment by lbb1991** [comment]
<br />
<b>Fatal error</b>:  Uncaught exception 'LogicException' with message 'Class Tudou could not be loaded' in D:\phpStudy\WWW\test\parserVideo.class.php:118
Stack trace:
#0 D:\phpStudy\WWW\test\parserVideo.class.php(118): spl_autoload('Tudou')
#1 D:\phpStudy\WWW\test\parserVideo.class.php(29): ParserVideo::_parseTudou('http://www.tudo...')
#2 D:\phpStudy\WWW\test\getVideo.php(6): ParserVideo::parse('http://www.tudo...')
#3 D:\phpStudy\WWW\test\getVideo.php(13): debug('http://www.tudo...')
#4 {main}
  thrown in <b>D:\phpStudy\WWW\test\parserVideo.class.php</b> on line <b>118</b><br />

**Comment by lbb1991** [comment]
你好 报这个错误肿么解决？我google了没有相关的错误资料，看源代码也不甚看懂。谢谢！

**Comment by keygle** [comment]
Tudou 没加载？ tudou.class.php 这个文件你看core文件夹下有吗？

**Comment by limho0202** [comment]
要解析出爱奇艺 m3u8要怎么整呢 ？ 能播出来吗？

**Comment by keygle** [comment]
看一下其他的解析方案吧，我很久没看了，而且 爱奇艺的 key 老换。
